### ISSUE TITLE
Problème avec le formatage des liens

### ISSUE THREAD

**Issue by Grifed-source** [oriionn/quecto#5]
![image](https://github.com/oriionn/quecto/assets/68700461/4eb86439-2772-4666-a56b-7cf7e138293e)

dans la commande par défaut de docker :

docker run -d \
  -p 80:3000 \
  -e DOMAIN=http://localhost/ \
  -e DB_TYPE=json \
  -e DB_JSON_PATH=./db.json \
  --name quecto \
  oriionn/quecto
  
  quand ça fait le nouveau lien ça fait un // ce qui fait que l'url est invalide

**Comment by oriionn** [comment]
Dans la configuration docker par défaut, il n'y pas de / sur le localhost,

Cf.
![githubscreen1](https://cdn.discordapp.com/attachments/1003011004738850956/1138939867917713468/image.png)
![githubscreen2](https://cdn.discordapp.com/attachments/1003011004738850956/1138939868152615114/image.png)
