### ISSUE TITLE
Affichage des ports dans les logs

### ISSUE THREAD

**Issue by Grifed-source** [oriionn/quecto#6]
![image](https://github.com/oriionn/quecto/assets/68700461/2b34342b-7d31-4933-936c-9afbc859f1e3)

Les logs de quecto n'affichent pas correctement le port dans les logs

**Comment by oriionn** [comment]
Peux-tu réessayer ?

**Comment by Grifed-source** [comment]
![image](https://github.com/oriionn/quecto/assets/68700461/85c8ba74-b6ca-4fab-a18e-07255ca8fc99)
